FROM python:3.7
MAINTAINER prem.it.rits@gmail.com
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install -r requirements.txt
ADD . /usr/src/app
ENTRYPOINT [ "python", "manage.py" ]
CMD [ "migrate" ] 
